version: '3.7'

services:
    app:
        container_name: jourloy-backend
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/app
            - /app/node_modules
        command: yarn dev
        env_file:
            - .env
        ports:
            - "${PORT}:${PORT}"
        restart: always

volumes:
    app:
